### ISSUE TITLE
Compilation errors fyrox::utils::log etc. 

### ISSUE THREAD

**Issue by tot-ra** [mrDIMAS/FishFolly#1]
I think there were some breaking changes in the engine that broke installation here.
Or did I miss something?

```
(v1) ➜  FishFolly git:(main) cargo run --package editor --release
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
   Compiling fyrox-ui v0.22.0 (/Users/artjom/git/Fyrox/fyrox-ui)
   Compiling fyrox v0.31.0 (/Users/artjom/git/Fyrox)
   Compiling fyroxed_base v0.18.0 (/Users/artjom/git/Fyrox/editor)
   Compiling fish_fall v0.1.0 (/Users/artjom/git/FishFolly/game)
error[E0432]: unresolved import `fyrox::utils::log`
  --> game/src/lib.rs:14:12
   |
14 |     utils::log::Log,
   |            ^^^ could not find `log` in `utils`

error[E0432]: unresolved imports `fyrox::scene::node::TypeUuidProvider`, `fyrox::utils::log`
  --> game/src/bot.rs:15:22
   |
15 |         node::{Node, TypeUuidProvider},
   |                      ^^^^^^^^^^^^^^^^ no `TypeUuidProvider` in `scene::node`
...
20 |         log::Log,
   |         ^^^ could not find `log` in `utils`

error[E0432]: unresolved imports `fyrox::scene::node::TypeUuidProvider`, `fyrox::utils::log`
  --> game/src/camera.rs:18:22
   |
18 |         node::{Node, TypeUuidProvider},
   |                      ^^^^^^^^^^^^^^^^ no `TypeUuidProvider` in `scene::node`
...
21 |     utils::log::Log,
   |            ^^^ could not find `log` in `utils`

error[E0432]: unresolved imports `fyrox::engine::resource_manager`, `fyrox::scene::node::TypeUuidProvider`, `fyrox::utils::log`
  --> game/src/cannon.rs:9:13
   |
9  |     engine::resource_manager::ResourceManager,
   |             ^^^^^^^^^^^^^^^^ could not find `resource_manager` in `engine`
...
12 |     scene::{node::TypeUuidProvider, rigidbody::RigidBody},
   |             ^^^^^^^^^^^^^^^^^^^^^^ no `TypeUuidProvider` in `scene::node`
13 |     script::{ScriptContext, ScriptTrait},
14 |     utils::log::Log,
   |            ^^^ could not find `log` in `utils`

error[E0432]: unresolved import `fyrox::scene::node::TypeUuidProvider`
  --> game/src/jumper.rs:12:33
   |
12 |     scene::{collider::Collider, node::TypeUuidProvider, rigidbody::RigidBody},
   |                                 ^^^^^^^^^^^^^^^^^^^^^^ no `TypeUuidProvider` in `scene::node`

error[E0432]: unresolved import `fyrox::scene::node::TypeUuidProvider`
  --> game/src/obstacle.rs:11:13
   |
11 |     scene::{node::TypeUuidProvider, rigidbody::RigidBody},
   |             ^^^^^^^^^^^^^^^^^^^^^^ no `TypeUuidProvider` in `scene::node`

error[E0432]: unresolved imports `fyrox::event::VirtualKeyCode`, `fyrox::scene::node::TypeUuidProvider`, `fyrox::utils::log`
  --> game/src/player.rs:13:27
   |
13 |     event::{ElementState, VirtualKeyCode, WindowEvent},
   |                           ^^^^^^^^^^^^^^ no `VirtualKeyCode` in `event`
...
18 |         node::{Node, TypeUuidProvider},
   |                      ^^^^^^^^^^^^^^^^ no `TypeUuidProvider` in `scene::node`
...
22 |     utils::log::Log,
   |            ^^^ could not find `log` in `utils`

error[E0432]: unresolved import `fyrox::scene::node::TypeUuidProvider`
  --> game/src/ragdoll/mod.rs:14:22
   |
14 |         node::{Node, TypeUuidProvider},
   |                      ^^^^^^^^^^^^^^^^ no `TypeUuidProvider` in `scene::node`

error[E0432]: unresolved import `fyrox::scene::node::TypeUuidProvider`
  --> game/src/ragdoll/link.rs:11:25
   |
11 |     scene::{node::Node, node::TypeUuidProvider},
   |                         ^^^^^^^^^^^^^^^^^^^^^^ no `TypeUuidProvider` in `scene::node`
   |
   = help: consider importing this unresolved item instead:
           crate::ragdoll::TypeUuidProvider

error[E0432]: unresolved import `fyrox::scene::node::TypeUuidProvider`
  --> game/src/respawn.rs:13:5
   |
13 |     scene::node::TypeUuidProvider,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TypeUuidProvider` in `scene::node`

error[E0432]: unresolved imports `fyrox::engine::resource_manager`, `fyrox::scene::node::TypeUuidProvider`, `fyrox::utils::log`
  --> game/src/start.rs:6:13
   |
6  |     engine::resource_manager::ResourceManager,
   |             ^^^^^^^^^^^^^^^^ could not find `resource_manager` in `engine`
...
9  |     scene::node::TypeUuidProvider,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TypeUuidProvider` in `scene::node`
10 |     script::{ScriptContext, ScriptDeinitContext, ScriptTrait},
11 |     utils::log::Log,
   |            ^^^ could not find `log` in `utils`

error[E0432]: unresolved imports `fyrox::scene::node::TypeUuidProvider`, `fyrox::utils::log`
 --> game/src/target.rs:7:5
  |
7 |     scene::node::TypeUuidProvider,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TypeUuidProvider` in `scene::node`
8 |     script::{ScriptContext, ScriptDeinitContext, ScriptTrait},
9 |     utils::log::Log,
  |            ^^^ could not find `log` in `utils`

error[E0407]: method `restore_resources` is not a member of trait `ScriptTrait`
  --> game/src/cannon.rs:80:5
   |
80 | /     fn restore_resources(&mut self, resource_manager: ResourceManager) {
81 | |         resource_manager
82 | |             .state()
83 | |             .containers_mut()
84 | |             .models
85 | |             .try_restore_optional_resource(&mut self.ball_prefab);
86 | |     }
   | |_____^ not a member of trait `ScriptTrait`

error[E0407]: method `restore_resources` is not a member of trait `ScriptTrait`
  --> game/src/start.rs:58:5
   |
58 | /     fn restore_resources(&mut self, resource_manager: ResourceManager) {
59 | |         resource_manager
60 | |             .state()
61 | |             .containers_mut()
62 | |             .models
63 | |             .try_restore_optional_resource(&mut self.model);
64 | |     }
   | |_____^ not a member of trait `ScriptTrait`

Some errors have detailed explanations: E0407, E0432.
For more information about an error, try `rustc --explain E0407`.
error: could not compile `fish_fall` (lib) due to 14 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by mrDIMAS** [comment]
Afaik, it should compile with Fyrox 0.29, but that could be just a temporary solution. I'll fix this when I have time.
